### ISSUE TITLE
Add Title bar

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#1]
Currently the app looks like this
![title](https://user-images.githubusercontent.com/56266286/95651649-788c3d80-0b09-11eb-92ec-4d8d07378a75.JPG)
It has it's own title bar.
But we are not planning to use that.
So add a Title Bar in the HTML content (index.html) having 
App logo on the extreme left, 
Name of app in the middle and 
Minimize and Close buttons on extreme right.
Choose any sample logo for the app or if interested design one and add that.
Do not add the functionality to minimize and close yet.

**Comment by AlacritousCreature** [comment]
I want to work on it. May I?

**Comment by untrulynoxiusmj** [comment]
@AlacritousCreature go ahead

**Comment by untrulynoxiusmj** [comment]
@AlacritousCreature updates?

**Comment by AlacritousCreature** [comment]
hey! I am working on same. I put it in a hour.
