### ISSUE TITLE
Add functionality to minimize and close the app window 

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#10]
Title bar added in PR: [PR 9](https://github.com/GeekHaven/file-explorer/pull/9) 
Add functionality to minimize and close the app window using minimize and close buttons respectively

**Comment by ccsCoder** [comment]
I am interested to work on this. Would you please assign this to me ?

**Comment by untrulynoxiusmj** [comment]
@ccsCoder Thanks for your interest. However, this repo is part of an event being held exclusively for our organization.
Sorry for the inconvenience.

**Comment by alkatrivedi** [comment]
I would like to work on this. May I?

**Comment by untrulynoxiusmj** [comment]
@alkatrivedi go ahead

**Comment by untrulynoxiusmj** [comment]
@alkatrivedi updates?

**Comment by alkatrivedi** [comment]
@untrulynoxiusmj I have added the functionality and it is working fine with close button but minimization is not working. I tried each and every solution given over the internet but non of them works.
I am trying. Will show you the results by tomorrow.

**Comment by alkatrivedi** [comment]
@untrulynoxiusmj I have added the following code in render.js file everything is fine from my point of view still it is not working. Can you please check what's wrong?

![1](https://user-images.githubusercontent.com/58396306/96036724-808a0b80-0e82-11eb-8aa8-7ec4e316a1b9.PNG)

**Comment by untrulynoxiusmj** [comment]
I think you need to set enableRemoteModule as true in webPreferences

You can always use Developer tools to look for errors
 ( -> View -> Toggle Developer Tools ) 
If it still doesn't work, please attach screenshot of the error you're getting using Dev Tools

**Comment by alkatrivedi** [comment]
Yeah! It's working. Thanks.
