### ISSUE TITLE
Add a button in Title Bar to Toggle Developer Tools

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#11]
Title Bar added in : [PR 9](https://github.com/GeekHaven/file-explorer/pull/9)

**Comment by geeks5551** [comment]
@untrulynoxiusmj Can i work on this issue?

**Comment by untrulynoxiusmj** [comment]
@geeks5551 go ahead

**Comment by untrulynoxiusmj** [comment]
@geeks5551 updates?

**Comment by untrulynoxiusmj** [comment]
This issue is open for claims

**Comment by kumarmanish03** [comment]
Can it is Still open? I want to work on this

**Comment by untrulynoxiusmj** [comment]
@kumarmanish03 go ahead
