### ISSUE TITLE
Display files and folders in Home Directory on the HTML page

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#12]
Currently files and folders in Home Directory are being logged to the console
Display them on the HTML page (index.html)
Refer: [PR 5](https://github.com/GeekHaven/file-explorer/pull/5)

**Comment by geeks5551** [comment]
@untrulynoxiusmj can i work on this issue?

**Comment by untrulynoxiusmj** [comment]
@geeks5551 you already have one issue assigned in this repo
However no one else has commented. So if you want, you can make a PR for this one too.
But if any claims come up, then I will assign them this issue. Of course if you solve your assigned issue
before that, this issue will automatically be assigned to you.

**Comment by cosmoimai** [comment]
can you assign this to me?

**Comment by untrulynoxiusmj** [comment]
go ahead @cosmoimai

**Comment by untrulynoxiusmj** [comment]
@cosmoimai updates?

**Comment by cosmoimai** [comment]
actually in looking how to connect index.html with renderer.js i don't how to do that. So i reading the documentation that's why it is taking time. i will do it by today

**Comment by cosmoimai** [comment]
is this follows the jsx language??

**Comment by untrulynoxiusmj** [comment]
index.html is already linked with renderer.js
You can simply use DOM manipulation

**Comment by cosmoimai** [comment]
like appendchild method

**Comment by cosmoimai** [comment]
do I also have to do styling

**Comment by untrulynoxiusmj** [comment]
No
