### ISSUE TITLE
Add Feature : clicking on a directory (folder) displays contents of that directory in HTML

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#17]
Currently, contents of only Home directory are shown in HTML
Also a way to distinguish between directories and files has been added
Add a feature :
**If a user clicks a directory (folder), display contents of that directory on HTML.**
Example:
Suppose Home Directory : C:\users\username
Then all files and folders of C:\users\username are displayed on HTML
Assume there is a folder Downloads in the Home directory
So what we need is that If user clicks on Downloads, all content of C:\users\username\Downloads 
is displayed on the HTML. 
Again if C:\users\username\Downloads  has some folder , say Movies
then display content of C:\users\username\Downloads\Movies  if a user clicks on Movies
and so on ....

**Comment by cosmoimai** [comment]
can you assign this to me?

**Comment by untrulynoxiusmj** [comment]
ok @cosmoimai

**Comment by untrulynoxiusmj** [comment]
@cosmoimai updates?

**Comment by cosmoimai** [comment]
currently in finding a way to apply that open function in the li node.

**Comment by cosmoimai** [comment]
I will do it by today
