### ISSUE TITLE
Add Feature : clicking on a file opens that file in default application used by OS

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#18]
Add a feature :
If a user clicks on a file, open that file in default application used by OS
Example:
Suppose Directory : C:\users\username 
Then all files and folders of C:\users\username are displayed on HTML
Assume there is a file image.jpg in Home directory
So what we need is that If user clicks on image.jpg , then C:\users\username\image.jpg is opened in
default application

**Comment by prince-7** [comment]
I would like to work on this

**Comment by untrulynoxiusmj** [comment]
Go ahead @prince-7
