### ISSUE TITLE
Add navigation bar

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#19]
Refer : [sketch](https://github.com/GeekHaven/file-explorer/blob/master/images/sketch.png)

Add Go back, Go forward buttons
An input which will display Directory currently open in App (Keep it disabled for now)
A button Go 
No functionality has to be added yet.
Only HTML and CSS

**Comment by kumarmanish03** [comment]
I want to work on it. Also i will soon create a pr for #11 it is done

**Comment by untrulynoxiusmj** [comment]
@kumarmanish03 updates?

**Comment by kumarmanish03** [comment]
Working on it, would make a pr soon

**Comment by Parasagrawal** [comment]
i want to work on this issue

**Comment by untrulynoxiusmj** [comment]
@kumarmanish03 deadline of 2 days is over

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal go ahead

**Comment by Parasagrawal** [comment]
can you explain this question , what i have to do

**Comment by untrulynoxiusmj** [comment]
![sketch](https://user-images.githubusercontent.com/56266286/96358825-2c548500-1129-11eb-8c0d-a7b081e5ff93.png)

You need to add the highlighted part in the HTML page ( index.html )
i.e. 
Go back, Go forward buttons
An input which will display Directory currently open in App (Keep it disabled for now)
A button Go
No functionality has to be added yet.

**Comment by kumarmanish03** [comment]
Hey @untrulynoxiusmj  I want to do this, If open assign to me

**Comment by Codedude1** [comment]
Can I work on this?
