### ISSUE TITLE
Implement functionality to Go back and Go forward

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#26]
Refer [PR 25](https://github.com/GeekHaven/file-explorer/pull/25)
navigation bar is added in this PR
there are elements for go back and go forward in HTML
Implement functionality to Go back and Go forward 

Refer [PR 24](https://github.com/GeekHaven/file-explorer/pull/24)  and [ISSUE 17](https://github.com/GeekHaven/file-explorer/issues/17)

Suppose Directory : C:\users\username
Then all files and folders of C:\users\username are displayed on HTML
Assume there is a folder Downloads in the C:\users\username directory
So now If user clicks on Downloads, all content of C:\users\username\Downloads is displayed on the HTML.
What we need is that if user clicks go back (element), it displays content of the previously opened directory i.e. C:\users\username

Again if C:\users\username\Downloads is being displayed and it has some folder , say Movies
then content of C:\users\username\Downloads\Movies is displayed if a user clicks on Movies
if we click go back: display content of C:\users\username\Downloads
And after that if we click go forward: display content of C:\users\username\Downloads\Movie

feel free to ask any doubts in the issue description or anything else

**Comment by Parasagrawal** [comment]
can i work on this

**Comment by prince-7** [comment]
I would like to work on this

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal go ahead

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal updates?

**Comment by Parasagrawal** [comment]
working

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal make sure to keep your fork in sync to the original repository

**Comment by Parasagrawal** [comment]
i have tried , but all method is not working. Can you give me hint??

**Comment by Parasagrawal** [comment]
i have tried, but what all i search on internet is not working. so can you give me hint??

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal you can keep track of directories being visited by user
and implement functionality to go back and go forward using that

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal are you still working on it ?

**Comment by Parasagrawal** [comment]
I am unable to complete this task ,so please  assign to other person

**Comment by untrulynoxiusmj** [comment]
> I would like to work on this

@prince-7 do you want to work on this issue

**Comment by prince-7** [comment]
@untrulynoxiusmj alright, assign me.
