### ISSUE TITLE
Display contents of directory in the input field if user clicks GO

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#28]
Refer [PR 25](https://github.com/GeekHaven/file-explorer/pull/25)
We have an input field here for current directory
Display contents of a directory that user has entered in that input field after user clicks  GO 
Add proper error handlers

**Comment by prince-7** [comment]
I would like to work on this

**Comment by untrulynoxiusmj** [comment]
@prince-7 go ahead

**Comment by prince-7** [comment]
one question, the result should appear only if the directory is present in the current folder, right?

**Comment by untrulynoxiusmj** [comment]
No, it should display result for any valid directory
There is no restriction
