### ISSUE TITLE
Design navigation bar

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#36]
![cr](https://user-images.githubusercontent.com/56266286/97083068-735fe000-162b-11eb-87eb-09756a66628f.JPG)

Design the highlighted part

**Comment by Parasagrawal** [comment]
can i work on this

**Comment by Parasagrawal** [comment]
this pr is same what i done previously

**Comment by untrulynoxiusmj** [comment]
@Parasagrawal go ahead
You have to style the navigation bar
