### ISSUE TITLE
Distinguish between directories and files

### ISSUE THREAD

**Issue by untrulynoxiusmj** [GeekHaven/file-explorer#6]
Currently getFilesandFolder function prints all files and folders in the home directory without distinguishing between them
Distinguish between directories and files and log them to console seperately.

**Comment by mustafamasvi** [comment]
@untrulynoxiusmj  Raised PR for the same.
Please check

**Comment by untrulynoxiusmj** [comment]
@mustafamasvi Thanks for your interest. However, this repo is part of an event being held exclusively for our organization.
 I will have to close that Pull Request
Sorry for the inconvenience.

**Comment by CadencePrestissimo** [comment]
can I work on it ?

**Comment by untrulynoxiusmj** [comment]
@CadencePrestissimo go ahead

**Comment by CadencePrestissimo** [comment]
Please check it , I am not sure if its completely right , then tell me accordingly , I will correct it !

**Comment by untrulynoxiusmj** [comment]
@CadencePrestissimo you received a comment on your PR
any updates?

**Comment by CadencePrestissimo** [comment]
trying to solve this error
